# Generated by Django 4.1.6 on 2023-02-09 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="comentarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("comentario", models.CharField(max_length=100)),
                ("reaccion", models.CharField(max_length=50)),
                ("fecha", models.PositiveBigIntegerField()),
            ],
        ),
    ]
